---
- name: installing software 
  hosts: all
  tasks:
    - name: install sft
      apt:
        name: "{{item.a}}"
        state: "{{item.b}}"
        update_cache: "{{item.c}}"
      with_items:
        - {a: git,b: absent,c: no} 
        - {a: maven,b: absent,c: no}
        - {a: tree,b: present,c: yes}

...
