---
- name: install/uninstall apache2
  hosts: all
  tasks:
    - name: install
      apt:
        name: apache2
        state: present
        update_cache: yes
      notify: check url responce


    - name: edit index file
      copy:
        content: "wellcome to my picasa"
        dest: /var/www/html/index.html
      notify: restart apache2

  handlers:
    - name: restart apache2
      service:
        name: apache2
        state: restarted

    - name: check url responce
      uri:
        url: "{{item}}"
        status_code: 200
      with_items:
        - http://172.31.3.92
        - http://172.31.9.15

...
