---
- name: creating user and create file in user home dir
  hosts: all
  become: yes
  tasks:
    - name: cretae user
      user:
        name: "{{a}}"
        password: "{{b}}"
        uid: "{{c}}"
        comment: "{{d}}"
        home: "{{e}}"
        

    - name: create file in home dir
      file:
        name: "{{f}}"
        state: "{{g}}"


...
